Repository rugii913/b3backoffice, pull requests merged in 2024-01, with the labels that each got.

#1 PR feature/project-init
  .gitignore
  README.md
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/kotlin/com/b3backoffice/B3backofficeApplication.kt
  src/main/kotlin/com/b3backoffice/infra/security/SecurityConfig.kt
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/kotlin/com/b3backoffice/B3backofficeApplicationTests.kt
Labels: documentation, enhancement

#5 PR feature/project-init-modified - feature/project-init 누락 부분 추가
  build.gradle.kts
  src/main/kotlin/com/b3backoffice/infra/security/SecurityConfig.kt
Labels: enhancement

#6 PR feature/documentation - README.md에 API 명세, ERD 추가
  README.md
  documents/api-specification-comment-v1.jpg
  documents/api-specification-notice-v1.jpg
  documents/api-specification-review-v1.jpg
  documents/api-specification-user-v1.jpg
  documents/erd-v1.png
Labels: documentation

#7 PR feature/entity - entity 작성
  src/main/kotlin/com/b3backoffice/domain/comment/model/Comment.kt
  src/main/kotlin/com/b3backoffice/domain/notice/model/Notice.kt
  src/main/kotlin/com/b3backoffice/domain/review/model/CuisineCategory.kt
  src/main/kotlin/com/b3backoffice/domain/review/model/Review.kt
  src/main/kotlin/com/b3backoffice/domain/shared/model/BaseEntity.kt
  src/main/kotlin/com/b3backoffice/domain/user/model/Profile.kt
  src/main/kotlin/com/b3backoffice/domain/user/model/User.kt
  src/main/kotlin/com/b3backoffice/domain/user/model/UserRole.kt
Labels: enhancement

#13 PR feature/swagger-config - Swagger 설정 추가
  src/main/kotlin/com/b3backoffice/infra/swagger/SwaggerConfig.kt
Labels: enhancement

#16 PR feature/erd-and-user-entity - User 엔티티의 테이블 지정 누락 수정, ERD 수정
  documents/erd-v1.png
  src/main/kotlin/com/b3backoffice/domain/user/model/User.kt
Labels: documentation, enhancement

#17 Add Comment Controller, Service
  src/main/kotlin/com/b3backoffice/domain/comment/controller/CommentController.kt
  src/main/kotlin/com/b3backoffice/domain/comment/dto/CommentRequest.kt
  src/main/kotlin/com/b3backoffice/domain/comment/dto/CommentResponse.kt
  src/main/kotlin/com/b3backoffice/domain/comment/model/Comment.kt
  src/main/kotlin/com/b3backoffice/domain/comment/repository/CommentRepository.kt
  src/main/kotlin/com/b3backoffice/domain/comment/service/CommentService.kt
Labels: enhancement

#19 PR feature/db-schema
  .gitignore
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: enhancement

#20 Feature/signup
  build.gradle.kts
  src/main/kotlin/com/b3backoffice/domain/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/b3backoffice/domain/exception/InvalidCredentialException.kt
  src/main/kotlin/com/b3backoffice/domain/exception/ModelNotFoundException.kt
  src/main/kotlin/com/b3backoffice/domain/exception/dto/ErrorDto.kt
  src/main/kotlin/com/b3backoffice/domain/user/controller/UserController.kt
  src/main/kotlin/com/b3backoffice/domain/user/dto/SignupArgument.kt
  src/main/kotlin/com/b3backoffice/domain/user/dto/UserDto.kt
  src/main/kotlin/com/b3backoffice/domain/user/repositiry/UserRepository.kt
  src/main/kotlin/com/b3backoffice/domain/user/service/UserService.kt
  src/main/kotlin/com/b3backoffice/domain/user/service/UserServiceImpl.kt
  src/main/kotlin/com/b3backoffice/infra/security/PasswordEncoderConfig.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/JwtPlugin.kt
  src/main/resources/application.yml
Labels: enhancement

#23 feature/login
  src/main/kotlin/com/b3backoffice/domain/user/controller/UserController.kt
  src/main/kotlin/com/b3backoffice/domain/user/dto/LoginArgument.kt
  src/main/kotlin/com/b3backoffice/domain/user/dto/LoginDto.kt
  src/main/kotlin/com/b3backoffice/domain/user/repositiry/UserRepository.kt
  src/main/kotlin/com/b3backoffice/domain/user/service/UserService.kt
  src/main/kotlin/com/b3backoffice/domain/user/service/UserServiceImpl.kt
Labels: enhancement

#22 PR feature/review-controller-dto
  src/main/kotlin/com/b3backoffice/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/b3backoffice/domain/review/dto/ReviewCreateRequest.kt
  src/main/kotlin/com/b3backoffice/domain/review/dto/ReviewResponse.kt
  src/main/kotlin/com/b3backoffice/domain/review/dto/ReviewUpdateRequest.kt
  src/main/kotlin/com/b3backoffice/domain/review/model/CuisineCategory.kt
Labels: enhancement

#24 Fix comment service
  src/main/kotlin/com/b3backoffice/domain/comment/controller/CommentController.kt
  src/main/kotlin/com/b3backoffice/domain/comment/service/CommentService.kt
  src/main/kotlin/com/b3backoffice/domain/exception/DeletedCommentException.kt
  src/main/kotlin/com/b3backoffice/domain/exception/GlobalExceptionHandler.kt
Labels: enhancement

#25 Add update user profile
  src/main/kotlin/com/b3backoffice/domain/comment/service/CommentService.kt
  src/main/kotlin/com/b3backoffice/domain/user/controller/UserController.kt
  src/main/kotlin/com/b3backoffice/domain/user/dto/UpdateProfileArgument.kt
  src/main/kotlin/com/b3backoffice/domain/user/service/UserService.kt
  src/main/kotlin/com/b3backoffice/domain/user/service/UserServiceImpl.kt
Labels: enhancement

#26 signup-add-verification, JWT Authentication
  src/main/kotlin/com/b3backoffice/domain/user/controller/UserController.kt
  src/main/kotlin/com/b3backoffice/domain/user/dto/SignupArgument.kt
  src/main/kotlin/com/b3backoffice/infra/security/UserPrincipal.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/JwtAuthenticationToken.kt
Labels: enhancement

#27 PR feature/review/repository-service-controller - Review 3 tier layer 연결
  src/main/kotlin/com/b3backoffice/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/b3backoffice/domain/review/model/Review.kt
  src/main/kotlin/com/b3backoffice/domain/review/repository/ReviewRepository.kt
  src/main/kotlin/com/b3backoffice/domain/review/service/ReviewService.kt
Labels: enhancement

#28 fix: JWT Authentication
  src/main/kotlin/com/b3backoffice/infra/security/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/com/b3backoffice/infra/security/SecurityConfig.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/JwtPlugin.kt
Labels: enhancement

#29 Feature/heart
  src/main/kotlin/com/b3backoffice/domain/heart/controller/HeartController.kt
  src/main/kotlin/com/b3backoffice/domain/heart/dto/HeartResponse.kt
  src/main/kotlin/com/b3backoffice/domain/heart/model/Heart.kt
  src/main/kotlin/com/b3backoffice/domain/heart/repository/HeartRepository.kt
  src/main/kotlin/com/b3backoffice/domain/heart/service/HeartService.kt
  src/main/kotlin/com/b3backoffice/domain/review/dto/ReviewResponse.kt
  src/main/kotlin/com/b3backoffice/domain/review/model/Review.kt
Labels: enhancement

#31 PR Feature/simple-logout - 로그아웃을 단순한 방식으로 구현
  src/main/kotlin/com/b3backoffice/domain/user/controller/UserController.kt
  src/main/kotlin/com/b3backoffice/infra/security/SecurityConfig.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/exception/InvalidatedTokenException.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/exception/InvalidatedTokenExceptionFilter.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/model/InvalidatedToken.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/repository/InvalidatedTokenRepository.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/service/TokenInvalidationService.kt
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: enhancement

#33 Fix Comment CRUD, Update User Profile
  src/main/kotlin/com/b3backoffice/domain/comment/controller/CommentController.kt
  src/main/kotlin/com/b3backoffice/domain/comment/dto/CommentRequest.kt
  src/main/kotlin/com/b3backoffice/domain/comment/dto/CommentResponse.kt
  src/main/kotlin/com/b3backoffice/domain/comment/repository/CommentRepository.kt
  src/main/kotlin/com/b3backoffice/domain/comment/service/CommentService.kt
  src/main/kotlin/com/b3backoffice/domain/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/b3backoffice/domain/exception/UnauthorizedException.kt
  src/main/kotlin/com/b3backoffice/domain/user/controller/UserController.kt
  src/main/kotlin/com/b3backoffice/domain/user/service/UserServiceImpl.kt
Labels: enhancement

#34 Feature/#8
  src/main/kotlin/com/b3backoffice/domain/notice/controller/NoticeController.kt
  src/main/kotlin/com/b3backoffice/domain/notice/dto/CreateNoticeRequest.kt
  src/main/kotlin/com/b3backoffice/domain/notice/dto/NoticeResponse.kt
  src/main/kotlin/com/b3backoffice/domain/notice/dto/UpdateNoticeRequest.kt
  src/main/kotlin/com/b3backoffice/domain/notice/model/Notice.kt
  src/main/kotlin/com/b3backoffice/domain/notice/repository/NoticeRepository.kt
  src/main/kotlin/com/b3backoffice/domain/notice/service/NoticeService.kt
Labels: enhancement

#37 PR feature/db-schema - 로컬 H2 DB 테이블 스키마 추가 및 수정
  src/main/resources/schema.sql
Labels: enhancement

#40 PR Feature/documentation - 변경사항 문서화 반영(API 명세, ERD, README 수정)
  README.md
  documents/api-specification-user-v1.jpg
  documents/api-specification-v1-comment.jpg
  documents/api-specification-v1-notice.jpg
  documents/api-specification-v1-review.jpg
  documents/api-specification-v1.5-heart.jpg
  documents/api-specification-v1.5-user.jpg
  documents/erd-v1.5.png
  documents/erd-v1.png
Labels: documentation

#38 PR Feature/review/validation-and-exception - Review 관련 request 검증 및 service에서 던지는 예외 처리 + 목록 조회 시 페이징 처리
  src/main/kotlin/com/b3backoffice/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/b3backoffice/domain/review/dto/ReviewCreateRequest.kt
  src/main/kotlin/com/b3backoffice/domain/review/dto/ReviewUpdateRequest.kt
  src/main/kotlin/com/b3backoffice/domain/review/model/Review.kt
  src/main/kotlin/com/b3backoffice/domain/review/repository/ReviewRepository.kt
  src/main/kotlin/com/b3backoffice/domain/review/service/ReviewService.kt
  src/main/resources/data.sql
Labels: enhancement

#45 PR feature/authorization-config - Security 설정 변경, 접근 URI 제한, @ EnableMethodSecurity
  src/main/kotlin/com/b3backoffice/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/b3backoffice/infra/security/CustomAccessDeniedHandler.kt
  src/main/kotlin/com/b3backoffice/infra/security/SecurityConfig.kt
  src/main/resources/data.sql
Labels: enhancement

#47 Notice 역할 기반 접근 제어
  src/main/kotlin/com/b3backoffice/domain/notice/controller/NoticeController.kt
Labels: enhancement

#44 PR feature/past-password
  src/main/kotlin/com/b3backoffice/domain/user/controller/UserController.kt
  src/main/kotlin/com/b3backoffice/domain/user/dto/SignupArgument.kt
  src/main/kotlin/com/b3backoffice/domain/user/dto/UpdatePasswordArgument.kt
  src/main/kotlin/com/b3backoffice/domain/user/model/PastPassword.kt
  src/main/kotlin/com/b3backoffice/domain/user/model/User.kt
  src/main/kotlin/com/b3backoffice/domain/user/repositiry/PastPasswordRepository.kt
  src/main/kotlin/com/b3backoffice/domain/user/service/UserService.kt
  src/main/kotlin/com/b3backoffice/domain/user/service/UserServiceImpl.kt
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: enhancement

#52 admin일 경우 모든 review 수정 및 삭제가능
  src/main/kotlin/com/b3backoffice/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/b3backoffice/domain/review/service/ReviewService.kt
Labels: enhancement

#51 Comment Role 인가
  src/main/kotlin/com/b3backoffice/domain/comment/controller/AdminCommentController.kt
  src/main/kotlin/com/b3backoffice/domain/comment/controller/CommentController.kt
  src/main/kotlin/com/b3backoffice/domain/comment/service/CommentService.kt
Labels: enhancement

#53 PR feature/refresh-token
  http-test/api-admin-test.http
  http-test/api-common-test.http
  http-test/http-client.private.env.json
  src/main/kotlin/com/b3backoffice/domain/auth/controller/AuthController.kt
  src/main/kotlin/com/b3backoffice/domain/auth/dto/ReissueAccessTokenRequest.kt
  src/main/kotlin/com/b3backoffice/domain/auth/dto/ReissueAccessTokenResponse.kt
  src/main/kotlin/com/b3backoffice/domain/auth/exception/InvalidatedTokenException.kt
  src/main/kotlin/com/b3backoffice/domain/auth/model/InvalidatedToken.kt
  src/main/kotlin/com/b3backoffice/domain/auth/repository/InvalidatedTokenRepository.kt
  src/main/kotlin/com/b3backoffice/domain/auth/service/AuthService.kt
  src/main/kotlin/com/b3backoffice/domain/auth/service/TokenInvalidationService.kt
  src/main/kotlin/com/b3backoffice/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/b3backoffice/domain/user/controller/UserController.kt
  src/main/kotlin/com/b3backoffice/domain/user/dto/LoginDto.kt
  src/main/kotlin/com/b3backoffice/domain/user/dto/LogoutArgument.kt
  src/main/kotlin/com/b3backoffice/domain/user/service/UserServiceImpl.kt
  src/main/kotlin/com/b3backoffice/infra/security/SecurityConfig.kt
  src/main/kotlin/com/b3backoffice/infra/security/authFilter/InvalidatedTokenExceptionFilter.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/JwtPlugin.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/model/InvalidatedToken.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/repository/InvalidatedTokenRepository.kt
  src/main/kotlin/com/b3backoffice/infra/security/jwt/service/TokenInvalidationService.kt
  src/main/kotlin/com/b3backoffice/infra/swagger/SwaggerConfig.kt
  src/main/resources/application.yml
  src/main/resources/schema.sql
Labels: enhancement

#54 PR - README 변경 및 API 명세, ERD 그림 파일 변경
  README.md
  documents/api-specification-v1-comment.jpg
  documents/api-specification-v1-notice.jpg
  documents/api-specification-v1-review.jpg
  documents/api-specification-v1.5-user.jpg
  documents/api-specification-v2-admin-comment.jpg
  documents/api-specification-v2-admin-notice.jpg
  documents/api-specification-v2-admin-review.jpg
  documents/api-specification-v2-admin-user.jpg
  documents/api-specification-v2-common-comment.jpg
  documents/api-specification-v2-common-notice.jpg
  documents/api-specification-v2-common-review.jpg
  documents/api-specification-v2-common-user.jpg
  documents/api-specification-v2-heart.jpg
  documents/erd-v2.png
Labels: documentation
